pub const DEFAULT_BEGINNER_WIDTH: u32 = 9;
pub const DEFAULT_BEGINNER_HEIGHT: u32 = 9;
pub const DEFAULT_BEGINNER_NUM_MINES: u32 = 10;
pub const DEFAULT_BEGINNER_UI_WIDTH: f32 = 376.0;
pub const DEFAULT_BEGINNER_UI_HEIGHT: f32 = 498.0;

pub const DEFAULT_INTERMEDIATE_WIDTH: u32 = 16;
pub const DEFAULT_INTERMEDIATE_HEIGHT: u32 = 16;
pub const DEFAULT_INTERMEDIATE_NUM_MINES: u32 = 40;
pub const DEFAULT_INTERMEDIATE_UI_WIDTH: f32 = 655.0;
pub const DEFAULT_INTERMEDIATE_UI_HEIGHT: f32 = 778.0;

pub const DEFAULT_EXPERT_WIDTH: u32 = 30;
pub const DEFAULT_EXPERT_HEIGHT: u32 = 16;
pub const DEFAULT_EXPERT_NUM_MINES: u32 = 80;
pub const DEFAULT_EXPERT_UI_WIDTH: f32 = 1215.0;
pub const DEFAULT_EXPERT_UI_HEIGHT: f32 = 777.0;
